name: tag
on:
  push:
    tags:        
      - 'v*'

jobs:
  build: 
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install yq
        uses: mikefarah/yq@master

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: |
          TAG="${GITHUB_REF##*/}" make push-image

      - name: Deploy
        run: |
          TAG="${GITHUB_REF##*/}"
          BUILD_NUMBER=${GITHUB_RUN_NUMBER}

          make deploy
